#cloud-config
package_upgrade: true
packages:
    - docker.io
write_files:
    - owner: vadimivlev:vadimivlev
        path: /home/vadimivlev/text-processor/docker-compose.yml
        content: |
            version: "3"
            services: 
                text-processor-worker:
                    image: vadimivlev/text-processor-worker:latest
                    container_name: text-processor-worker
                    restart: unless-stopped
runcmd:
    #   - sudo apt install docker.io 
    - sudo systemctl start docker
    - sudo systemctl enable docker
    # docker post install. running without sudo.
    # Create the docker group.
    - sudo groupadd docker
    # Add your user to the docker group.
    - sudo usermod -aG docker vadimivlev
    - cd "/home/vadimivlev/text-processor"
    - docker-compose up -d

